/**
 * OrbitaliQ.DigitalWallet.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.3.409
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FullUserDto { 
    id?: string | null;
    readonly userName?: string | null;
    address?: string | null;
    balance?: number;
    birthDate?: string | null;
    chargeGatewaySettings?: string | null;
    city?: string | null;
    country?: string | null;
    email?: string | null;
    externalId?: string | null;
    firstName?: string | null;
    gateway?: string | null;
    gender?: string | null;
    isActive?: boolean;
    isChild?: boolean;
    isCreditCardPaired?: boolean;
    lastName?: string | null;
    limits?: string | null;
    lockoutEnd?: string | null;
    notes?: Array<string> | null;
    phoneNumber?: string | null;
    pmsData?: string | null;
    postcode?: string | null;
    resetPasswordToken?: string | null;
    roles?: Array<string> | null;
    unPaidAdults?: boolean;
    timestamp?: string | null;
}

