/**
 * OrbitaliQ.Payment.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.3.409
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Discount } from './discount';
import { InvoiceItem } from './invoiceItem';
import { VAT } from './vAT';


export interface InvoiceData { 
    invoiceNumber?: string | null;
    invoiceNotes?: string | null;
    header?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phone?: string | null;
    currency?: string | null;
    items?: Array<InvoiceItem> | null;
    discountModifier?: Discount;
    vatModifier?: VAT;
}

