/**
 * OrbitaliQ.Payment.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.5.506
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Discount } from './discount';


export interface InvoiceItem { 
    id?: string | null;
    index?: number;
    name?: string | null;
    description?: string | null;
    sku?: string | null;
    pricePerItem?: number;
    quantity?: number;
    itemDiscount?: Discount;
}

