/**
 * OrbitaliQ.Payment.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.3.409
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderPaymentModel { 
    orderConfirmation?: string | null;
    paymentMethodId?: string | null;
    userId?: string | null;
    notifySuccsessWebhookURI?: string | null;
}

