/**
 * OrbitaliQ.Payment.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.5.506
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Receipt { 
    accountId?: string | null;
    amount?: number;
    currency?: string | null;
    description?: string | null;
    externalId?: string | null;
    attachedData?: any | null;
    creationDate?: string;
    id?: string | null;
    confirmation?: string | null;
    userId?: string | null;
    paymentRetrefId?: string | null;
    invoiceNumber?: string | null;
    paymentMethodId?: string | null;
    attachedPaymentResponceData?: any | null;
}

